//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConnectionTable
    {
        public int ID { get; set; }
        public int SpecialtyAndSemesterID { get; set; }
        public int DisciplineID { get; set; }
    
        public virtual Discipline Discipline { get; set; }
        public virtual SpecialtyAndSemester SpecialtyAndSemester { get; set; }
    }
}
