//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpecialtyAndSemester
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SpecialtyAndSemester()
        {
            this.ConnectionTables = new HashSet<ConnectionTable>();
        }
    
        public int ID { get; set; }
        public string Specialty { get; set; }
        public int Semester { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConnectionTable> ConnectionTables { get; set; }
    }
}
